"""
Per-environment body-frame kinematic fit constants for the shield's
"heading_fit" prediction mode (see shield.py's GenericKeepoutShield
docstring and its kinematic_model parameter).

Generated by scripts/fit_kinematic_model.py, seed 0's
`*_riemannian_postfix` checkpoint, alpha=0.1/influence_radius=0.4, 6000
step-pairs per robot, disjoint fit/holdout split. On held-out data the
fitted model cuts median prediction error from 43-57% of the hazard radius
(current "world_xy" model) to 4-6%, and raises direction cosine similarity
with the true displacement from ~0 (car) / negative (point) to 0.93-0.9986
median -- see SESSION_HANDOFF.md for the full comparison table, including a
world-frame-only control fit (no heading) that lands in between (7-10% of
radius, still weak/mixed cosine), confirming heading is doing real work
rather than the improvement being explainable by scale recalibration alone.

These constants are checkpoint- and shield-config-specific (the robot's
actuation model doesn't change, but a different alpha/influence_radius
shield would produce a different intervened-vs-non-intervened mix in the
rollout used to fit them; the fit itself uses only non-intervened steps, so
it should be robust to that, but has not been validated against a
differently-configured shield). Treat a re-fit as needed if the shield
config or robot model changes materially.
"""

from typing import Dict, Tuple
import numpy as np

# disp_body ~= M @ a_xy + b, fit in the body frame defined by
# env.unwrapped.task.agent.mat's yaw (see resolve_heading in make_env.py).
_FITS: Dict[str, Tuple[np.ndarray, np.ndarray]] = {
    "SafetyCarGoal1-v0": (
        np.array([[0.0007129, -0.00076654],
                  [-0.01528566, -0.01486715]], dtype=np.float32),
        np.array([7.33066385e-05, -5.03080914e-05], dtype=np.float32),
    ),
    "SafetyPointGoal1-v0": (
        np.array([[1.27778668e-02, 1.03445673e-03],
                  [-1.42689260e-03, 4.01091285e-05]], dtype=np.float32),
        np.array([-0.00061374, 0.00285633], dtype=np.float32),
    ),
}


def get_body_frame_fit(env_id: str) -> Tuple[np.ndarray, np.ndarray]:
    """
    Look up the fitted (M, b) body-frame kinematic model for an env ID.

    Raises rather than falling back to an unfit default, since a shield
    silently reverting to some placeholder linear map would be exactly the
    kind of silent-degradation defect this project has repeatedly had to
    audit for (see D1 in CODE_AUDIT_AND_EXECUTION_PLAN.md).

    :param env_id: Safety-Gymnasium environment ID.
        :type env_id: str

    :return: (M, b) with M shape (2, 2), b shape (2,).
        :rtype: Tuple[np.ndarray, np.ndarray]

    :raises ValueError: If no fit is registered for this env_id.
    """
    if env_id not in _FITS:
        raise ValueError(
            f"No body-frame kinematic fit registered for env_id={env_id!r}. "
            f"Known envs: {sorted(_FITS)}. Run scripts/fit_kinematic_model.py "
            "against this env and add the result to _FITS before using "
            "kinematic_model='heading_fit' here -- failing loudly rather "
            "than silently using another robot's fit or an unfit default."
        )
    return _FITS[env_id]
